CREATE TABLE MEMBER_TBL(
    MEMBER_ID VARCHAR2(30) PRIMARY KEY,
    MEMBER_PW VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    MEMBER_AGE NUMBER,
    MEMBER_EMAIL VARCHAR2(40),
    MEMBER_PHONE VARCHAR2(20),
    MEMBER_ADDR VARCHAR2(200),
    MEMBER_GENDER CHAR(1) CHECK(MEMBER_GENDER IN('M','F')),
    MEMBER_HOBBY VARCHAR2(400),
    MEMBER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO MEMBER_TBL VALUES('khuser01', 'pass01', '일용자', 22, 'khuser@iei.or.kr',
'01011111111', '서울시 중구', 'M', '독서,수영,골프', DEFAULT);

SELECT * FROM MEMBER_TBL;
SELECT COUNT(*) FROM MEMBER_TBL;
SELECT COUNT(*) FROM MEMBER_TBL WHERE MEMBER_ID = 'khuser01' AND MEMBER_PW = 'pass01';

commit;