-- 게시판 공지사항
-- 제목, 내용, 작성자, 작성일, 조회수
CREATE TABLE NOTICE_TBL(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_SUBJECT VARCHAR2(200) NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
    NOTICE_WRITER VARCHAR2(50) NOT NULL,
    NOTICE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- 시분초 존재    
    VIEW_COUNT NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_NOTICENO;
DROP SEQUENCE SEQ_NOTICENO;

SELECT * FROM USER_SEQUENCES;
SELECT SEQ_NOTICENO.NEXTVAL FROM DUAL;
SELECT SEQ_NOTICENO.CURRVAL FROM DUAL;

SELECT * FROM NOTICE_TBL;
SELECT COUNT(*) FROM NOTICE_TBL;
SELECT * FROM NOTICE_TBL WHERE NOTICE_NO = 1;

INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 1번째', '1번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 2번째', '2번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 3번째', '3번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 4번째', '4번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 5번째', '5번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 6번째', '6번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 7번째', '7번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 8번째', '8번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 9번째', '9번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 10번째', '10번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 11번째', '11번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 12번째', '12번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 13번째', '13번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 14번째', '14번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 15번째', '15번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 16번째', '16번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 17번째', '17번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 18번째', '18번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 19번째', '19번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 20번째', '20번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 21번째', '21번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 22번째', '22번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 23번째', '23번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 24번째', '24번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 25번째', '25번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 26번째', '26번째 공지사항', 'admin', DEFAULT, DEFAULT);
INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL, '공지사항 27번째', '27번째 공지사항', 'admin', DEFAULT, DEFAULT);

-- 페이징 처리
SELECT ROWNUM, NOTICE_NO FROM NOTICE_TBL;

-- BETWEEN 1 AND 10을 11 AND 20으로 적용이 안됨..
SELECT ROWNUM, NOTICE_NO FROM NOTICE_TBL 
WHERE ROWNUM BETWEEN 1 AND 10 
ORDER BY NOTICE_NO DESC;

-- 함수 사용
SELECT * FROM (
SELECT ROW_NUMBER() OVER(ORDER BY NOTICE_NO DESC) AS NUM, NOTICE_NO FROM NOTICE_TBL) 
WHERE NUM BETWEEN 11 AND 20; 

SELECT * FROM (
SELECT ROW_NUMBER() OVER(ORDER BY NOTICE_NO DESC) AS NUM, NOTICE_TBL.* FROM NOTICE_TBL); 

SELECT * FROM (
SELECT ROW_NUMBER() OVER(ORDER BY NOTICE_NO DESC) AS NUM, NOTICE_TBL.* FROM NOTICE_TBL)
WHERE NUM BETWEEN 1 AND 10;

COMMIT;