-- 게시판 공지사항
-- 제목, 내용, 작성자, 작성일, 조회수
CREATE TABLE NOTICE_TBL(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_SUBJECT VARCHAR2(200) NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
    NOTICE_WRITER VARCHAR2(50) NOT NULL,
    NOTICE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- 시분초 존재    
    VIEW_COUNT NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_NOTICENO;
DROP SEQUENCE SEQ_NOTICENO;

SELECT * FROM USER_SEQUENCES;
SELECT SEQ_NOTICENO.NEXTVAL FROM DUAL;
SELECT SEQ_NOTICENO.CURRVAL FROM DUAL;

SELECT * FROM NOTICE_TBL;